---
---
// AUTO-GENERATED by Jekyll from _posts/ (only posts with category "5leagues").
// Do NOT edit by hand -- add a turn as an _posts/ Markdown file instead.
//
// Consumed by the Five Leagues app (five-leagues/overview.html) to list a
// campaign's turns. The "category" is emitted as "5Leagues-N" to match what
// that page already filters on; "url" is relative to /blog/ for the same reason.
const blogPosts = [
{%- assign turns = site.posts | where: "category", "5leagues" | sort: "date" | reverse -%}
{%- for t in turns %}
  {
    "id": {{ t.title | slugify | jsonify }},
    "title": {{ t.title | jsonify }},
    "date": {{ t.date | date: "%Y-%m-%d" | jsonify }},
    "category": {{ "5Leagues-" | append: t.campaign | jsonify }},
    "excerpt": {{ t.excerpt | jsonify }},
    "url": {{ t.url | remove_first: "/blog/" | jsonify }}
  }{%- unless forloop.last %},{%- endunless %}
{%- endfor %}
];
