---
---
// AUTO-GENERATED by Jekyll from five-leagues/_posts/ (posts with category "5leagues").
// Do NOT edit by hand -- add a turn as a five-leagues/_posts/ Markdown file instead.
//
// Consumed by the Five Leagues app (overview.html) to list a campaign's turns.
// "category" is emitted as "5Leagues-N" to match what that page filters on;
// "url" is the turn's full /five-leagues/turns/... address.
const blogPosts = [
{%- assign turns = site.posts | where: "category", "5leagues" | sort: "date" | reverse -%}
{%- for t in turns %}
  {
    "id": {{ t.title | slugify | jsonify }},
    "title": {{ t.title | jsonify }},
    "date": {{ t.date | date: "%Y-%m-%d" | jsonify }},
    "category": {{ "5Leagues-" | append: t.campaign | jsonify }},
    "excerpt": {{ t.excerpt | jsonify }},
    "url": {{ t.url | jsonify }}
  }{%- unless forloop.last %},{%- endunless %}
{%- endfor %}
];
